PYOBJ=../src/python_vol.c
CC = h5pcc
CFLAGS = -c -fno-strict-aliasing -Wmissing-include-dirs -O2 -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/common/software/python/2.7-anaconda-4.4/include/python2.7 -isystem/usr/common/software/python/2.7-anaconda-4.4/lib/python2.7/site-packages/numpy/core/include  -Wno-unused-variable  -Wno-strict-prototypes -I/usr/common/software/hdf5-parallel/hdf5-1.9.234/src

LDFLAGS = -L/usr/common/software/python/2.7-anaconda-4.4/lib -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic #-Wl,--verbose

objects = HDF5_file_create HDF5_file_open HDF5_objects_create HDF5_objects_open HDF5_dataset_read HDF5_dataset_write HDF5_file_create_parallel 

other_obj = python_vol	

all: $(objects)

$(objects): %: %.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $<

$(other_obj): ${PYOBJ}
	$(CC) $(CFLAGS) -c $@ $<

clean:
	rm HDF5_File_create HDF5_File_open HDF5_Objects_create HDF5_Objects_open HDF5_Dataset_read HDF5_Dataset_write HDF5_File_create_parallel *.o 
