#!/bin/bash
#swift -A http://127.0.0.1:8080/auth/v1.0 -U test:tester -K testing stat 
#swift -A http://127.0.0.1:8080/auth/v1.0 -U test:tester -K testing list
vr=$(swift -A http://127.0.0.1:8080/auth/v1.0 -U test:tester -K testing list)  
echo $vr
for it in $vr
do
 swift -A http://127.0.0.1:8080/auth/v1.0 -U test:tester -K testing delete $it
done
