#!/bin/bash
docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null
docker run -v /srv --name SWIFT_DATA busybox
docker run -d --security-opt seccomp=unconfined -p 12345:8080 --volumes-from SWIFT_DATA -t valiantljk/sciswift:v3
CID=$(docker ps --latest --quiet)
docker exec -it $CID bash -c "./usr/local/bin/startmain.sh &"
docker exec -it $CID bash
cd /build/sci-swift
git pull 

